version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Secret@1234
    volumes:
      - /Users/nikunj.ratanpara/docker_volume/pgdata:/var/lib/postgresql/data
