version: "3.2"

services:     
  zookeeperkafka:
    hostname: "zookeeperkafka"
    image: zookeeper
    restart: always
    ports:
      - 2182:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    ports:
      - 9093:9093
    environment:
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9092,OUTSIDE://${CM_LOCAL_IP}:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeperkafka:2181
      - ZOOKEEPER_IP=zookeeperkafka
      - ALLOW_PLAINTEXT_LISTENER=yes
    env_file:
      - ./.env
    volumes:
      - /Users/nikunj.ratanpara/docker_volume/kafka/kafka_data:/bitnami/kafka
    depends_on:
      - zookeeperkafka
    restart: on-failure